[manifest]
version = "1.1.1"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "obj/TitleParticle.lua"
pattern = '''
if self.y >= 300 then self.delete = true end -- i do not trust my deleting code at all
'''
position = "at"
payload = '''
if self.y >= 370 then self.delete = true end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/level/BEATROCK/HoleBackground.lua"
pattern = '''
	self.spawnTimer = self.spawnTimer - (cs.cBeat - self.lastbeat) / (savedata.options.accessibility.vfx == "full" and 1 or 2)
	self.lastbeat = cs.cBeat
'''
position = "before"
payload = '''
cs.cBeat = cs.cBeat or 0
cs.cBeat = cs.cBeat + dt/60
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/level/lawrence/LawrenceBG.lua"
pattern = '''
self.cumulativeAngle = self.cumulativeAngle + cs.p.angleDelta
'''
position = "at"
payload = '''
self.cumulativeAngle = self.cumulativeAngle + (cs.p and cs.p.angleDelta or 0)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/MinesweeperBG.lua"
pattern = '''
local time = cs.bgm:getBeat()
'''
position = "at"
payload = '''
local time = 1
if cs.bgm then
	time = cs.bgm:getBeat()
end
'''
match_indent = true