[manifest]
version = "1.1.1"
dump_lua = true
priority = 0

# level transition test stuff
[[patches]]
[patches.pattern]
target = "states/Results.lua"
pattern = '''
dpf.saveJson("savedata/playedlevels.json", self.playedLevelsJson)
'''
position = "after"
payload = '''
--self:goToHiddenLevel('levels/Finished levels/blowafuse/', 'BlowAFuseIntro')
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Results.lua"
pattern = '''
function st:changeToHidden()
'''
position = "before"
payload = '''
function st:goToHiddenLevel(levelPath, transitionState, variant)
    self.goToHidden = true
	self.transition = transitionState or 'NisenenIntro'
	self.filename = levelPath or 'levels/Finished levels/nisenen/'
	self.newVariant = variant or 'hard'
	
	-- Ratemod, restart on and no barely judgements should reset on hidden song entry
	self.rateMod = 1
	self.restartOn = 'none'
	--self.noBarelyJudgements = false
end
'''
match_indent = true

#cs variable looker
[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = '''
st:setFgDraw(function(self)
'''
position = "after"
payload = '''
--[[
	self.cseditor = imgui.Begin("CS Editor", nil, 0)
		imguiextra.drawTable(cs)
	imgui.End()]]
'''
match_indent = true

#unused/unfinished options
[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = '''
st:setUpdate(function(self,dt)
'''
position = "after"
payload = '''
if self.chimaera then
	self.menuMusicManager:stop()

	--[[cs = bs.load('BattleState')
	cs.bg = self.bg
	cs:init({{'chimaeraBoss', { ogx = 467, ogy = 153 }}}, {"The walls shift...",
		"A gust of wind rattles the room.",
		"Distant echoes.",
		"The ground trembles slightly.",
		"Shadows dance across the walls.",
		"Time seems to slow down.",
		"A faint rumble echoes around.",
		"The air feels heavy.",
		"Silence fills the space.",
		"A eerie calm settles.",
		"Cranky wants cornbread",
		"..."})]]

	cs = bs.load('WorldState')
	self.bg.delete = true
	cs:init('Mods/ExtraStuff/rooms/EraChimaeraRoom.json')
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Results.lua"
pattern = '''
self.options.allowInput = true
'''
position = "after"
payload = '''
if _G.extrastuff_baftransnext then
	_G.extrastuff_baftransnext = false
	self:goToHiddenLevel('levels/Finished levels/blowafuse/', 'BlowAFuseIntro', 'hard')
end
'''
match_indent = true
