[manifest]
version = "1.1.1"
dump_lua = true
priority = 0

# yeah no, im not organizing this
# that would require me to look through this awful thing

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
function st:startShowCatch(fish,new)
'''
position = "at"
payload = '''
function st:startShowCatch(fish,new,replay)
local replay = replay or false
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
function st:reset()
'''
position = "after"
payload = '''
self.forceShowRodneyText = false
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
if savedata.fishing.hasBook then
	self.caughtFish = fish
'''
position = "before"
payload = '''
if not replay then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
sdfunc.save()
'''
position = "after"
payload = '''
else
	self.caughtFish = fish
	self.forceShowRodneyText = true
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
flux.to(self.pauseMenu.pausePosition,60,{w=220}):ease("inOutExpo")
'''
position = "at"
payload = '''
local width = 220
if self.fishPerPage > 8 then
	width = 440
end
flux.to(self.pauseMenu.pausePosition,60,{w=width}):ease("inOutExpo")
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
local id = self.orderedFish[i]
'''
position = "after"
payload = '''
local index = i - startIndex
local columns = 1
if self.fishPerPage >= 5 and self.fishPerPage <= 8 then
    columns = 2
elseif self.fishPerPage > 8 then
    columns = 4
end

local spacingX = 110
local spacingY = 70

local col = index % columns
local row = math.floor(index / columns) - 1

local x = project.res.cx + (col - (columns-1)/2) * spacingX
y = 100 + row * spacingY
local scale = 1
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
local y = 100 + (i-startIndex-1) * 70
'''
position = "after"
payload = '''
local index = i - startIndex
local columns = 1
if self.fishPerPage >= 5 and self.fishPerPage <= 8 then
    columns = 2
elseif self.fishPerPage > 8 then
    columns = 4
end

local spacingX = 110
local spacingY = 70

local col = index % columns
local row = math.floor(index / columns) - 1

local x = project.res.cx + (col - (columns-1)/2) * spacingX
y = 100 + row * spacingY
local scale = 1
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
love.graphics.draw(self.fish[id].spr,project.res.cx + fishW,y + fishH,0,1,1,25)
'''
position = "at"
payload = '''
local imgW, imgH = self.fish[id].spr:getDimensions()
if extrasavedata.replayFish then
	local selectedFish = self.orderedFish[self.bookMenu.selection + ((self.bookPage - 1) * self.fishPerPage)]
	if (mouse.rx >= x - imgW/2 and mouse.rx <= x + imgW/2 and
	   mouse.ry >= y and mouse.ry <= y + imgH) or (selectedFish == id) then
		scale = 1.2
		if (mouse.pressed == -1 or maininput:pressed("accept")) and timesCaught then
			self:closeBook()
			self:startShowCatch(id,false,true)
		end
	end
end
love.graphics.draw(self.fish[id].spr,x,y + imgH/2,0,scale,scale, imgW/2, imgH/2)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
love.graphics.printf(fishText,1,y+42,(project.res.x-2),'center',0,1,1)
love.graphics.printf(fishText,3,y+42,(project.res.x-2),'center',0,1,1)
love.graphics.printf(fishText,2,y+41,(project.res.x-2),'center',0,1,1)
love.graphics.printf(fishText,2,y+43,(project.res.x-2),'center',0,1,1)
'''
position = "at"
payload = '''
love.graphics.printf(fishText,x-imgW*2-1,y+42,imgW*4,'center',0,1,1)
love.graphics.printf(fishText,x-imgW*2+1,y+42,imgW*4,'center',0,1,1)
love.graphics.printf(fishText,x-imgW*2,y+41,imgW*4,'center',0,1,1)
love.graphics.printf(fishText,x-imgW*2,y+43,imgW*4,'center',0,1,1)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
	love.graphics.printf(fishText,2,y+42,(project.res.x-2),'center',0,1,1)
end
'''
position = "at"
payload = '''
	love.graphics.printf(fishText,x-imgW*2,y+42,imgW*4,'center',0,1,1)
else
	local imgW, imgH = sprites.fishing.unknownfish:getDimensions()
	if (mouse.rx >= x - imgW/2 and mouse.rx <= x + imgW/2 and
	   mouse.ry >= y and mouse.ry <= y + imgH) or ((self.bookMenu.selection + ((self.bookPage - 1) * self.fishPerPage)) == i) then
		scale = 1.2
	end
	love.graphics.draw(sprites.fishing.unknownfish,x,y + imgH/2,0,scale,scale,25, 20)
	love.graphics.printf("Empty Slot",x-imgW*2,y+42,imgW*4,'center',0,1,1)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
self.pauseMenu:draw()
		local pp = self.pauseMenu.pausePosition
		if pp.w > 0 then
'''
position = "at"
payload = '''
		local pp = self.pauseMenu.pausePosition
		if pp.w <= 0 or not extrasavedata.fishingBookText then
			self.pauseMenu:draw()
		end
		if pp.w > 0 and self.bookPage ~= 0 then
if extrasavedata.fishingBookText then
	color()
	if self.fishPerPage <= 8 then
		love.graphics.draw(sprites.fishing.viewbook, 300, 180, 0, pp.w/220, 1, 325, 162)
		love.graphics.draw(sprites.fishing.viewbooktag, 300, 180, 0, pp.w/220, 1, 108, 162)
	else
		love.graphics.draw(sprites.fishing.viewbook2, 300, 180, 0, pp.w/440, 1, 217, 162)
		love.graphics.draw(sprites.fishing.viewbooktag, 300, 180, 0, pp.w/440, 1, 108, 162)
	end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
	love.graphics.setScissor()
end
'''
position = "at"
payload = '''
	love.graphics.setScissor()
elseif self.bookPage == 0 then
	color()
	local wmult = 0
	if self.fishPerPage <= 8 then
		wmult = helpers.clamp(pp.w/220, 0, 1)
	else
		wmult = helpers.clamp(pp.w/440, 0, 1)
	end
	local mx, my = mouse.rx, mouse.ry

	local x = 300
	local xoff = 0
	local y = 180
	local baseScale = 1
	local hoverScale = 1.08
	local scale = baseScale
	local dashScale = baseScale
	local bw, bh = 200, 200

	if mods["openocean"] and mods["openocean"].enabled then
		xoff = 110

		if (mx >= 410 - bw/2 * wmult and mx <= 410 + bw/2 * wmult --haha funny number, ok im going to kms
		and my >= y - bh/2 and my <= y + bh/2) or self.bookMenu.selection == 2 then
			dashScale = hoverScale
			if (mouse.pressed == -1 or maininput:pressed("accept")) then
				self:closeBook()
				self:startShowCatch("dash_book",false,true)
			end
		end
		if extrasavedata.fishingBookText then
			love.graphics.draw(sprites.fishing.dashfront,300, y,0,dashScale * wmult, dashScale,108-xoff, 162)
		end
	end
	
	if (mx >= 300 - xoff - bw/2 * wmult and mx <= 300 - xoff + bw/2 * wmult
	and my >= y - bh/2 and my <= y + bh/2) or self.bookMenu.selection == 1 then
		scale = hoverScale
		if (mouse.pressed == -1 or maininput:pressed("accept")) then
			self:closeBook()
			self:startShowCatch("book",false,true)
		end
	end
	if extrasavedata.fishingBookText then
		love.graphics.draw(sprites.fishing.bookfront,300, y,0,scale * wmult, scale,108+xoff, 162)
		love.graphics.draw(sprites.fishing.viewbooktag,300, 180,0,wmult, 1,108, 162)
	end
	if pp.w > 0 then
		love.graphics.setScissor(pp.x1-pp.w*0.5,pp.y,pp.w,pp.h)
		if not extrasavedata.fishingBookText then
			if mods["openocean"] and mods["openocean"].enabled then
				love.graphics.draw(sprites.fishing.dash_book,300+xoff, y,0,dashScale, dashScale,90, 90)
			end
			love.graphics.draw(self.spr.book,300-xoff, y,0,scale, scale,90, 90)
		end
		self.bookMenu:draw()
		love.graphics.setScissor()
	end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
self.bookMenu:addNumber('fish_bookPage',self,'bookPage',0,nil,{1,self.bookTotalPages},nil,self.bookTotalPages)
'''
position = "at"
payload = '''
for i = 1, self.fishPerPage do
	self.bookMenu:addOption('',function() end, 100)
end
if extrasavedata.replayFish then
	self.bookMenu:addNumber('fish_bookPage',self,'bookPage',0,nil,{0,self.bookTotalPages},nil,self.bookTotalPages)
else
	self.bookMenu:addNumber('fish_bookPage',self,'bookPage',0,nil,{1,self.bookTotalPages},nil,self.bookTotalPages)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
self.fishPerPage = 4
'''
position = "at"
payload = '''
self.fishPerPage = extrasavedata.fishPerPage
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
love.graphics.draw(self.spr.ditheredfish_eye, project.res.cx + fishW + self.ditheredfish.eyeoffset, y + fishH + math.random(-1, 1),0,1,1,25)
'''
position = "at"
payload = '''
--love.graphics.draw(self.fish[id].spr,x,y + imgH/2,0,scale,scale, imgW/2, imgH/2)
love.graphics.draw(self.spr.ditheredfish_eye, x + fishW + self.ditheredfish.eyeoffset, y + fishH + math.random(-1, 1),0,1,1,25)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
self.bookMenu:setSelection(1)
'''
position = "at"
payload = '''
self.bookMenu:setSelection(#self.bookMenu.options.main - 1)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Fishing.lua"
pattern = '''
if self.viewingBook then
'''
position = "after"
payload = '''
local num = 1
if mods["openocean"] and mods["openocean"].enabled then
	num = 2
end
if self.bookPage == 0 then
	if (self.bookMenu.selection > num) and (self.bookMenu.selection < self.fishPerPage + 1) then
		if maininput:pressed("menu_down") then
			self.bookMenu:setSelection(#self.bookMenu.options.main - 1)
		else
			self.bookMenu:setSelection(num)
		end
	end
end
'''
match_indent = true
