[manifest]
version = "1.1.1"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "levelformat/events/Gameplay/play.lua"
pattern = '''
cs.timingInfo.initial = {bpm = event.bpm, timeOffsetSeconds = event.offset, beatOffset = event.time}
if not love.filesystem.exists(cLevel..event.file) then
	cs:playbackError('Song file "' .. cLevel..event.file .. '" does not exist. Please ensure you typed the name correctly, and that it is in the right location.')
	return true
end
'''
position = "after"
payload = '''
local validEntries = {}
local entryList = {} -- {{ name = "...", index = N }}

table.insert(validEntries, {
    bpm = event.bpm,
    timeOffsetSeconds = event.offset,
    beatOffset = event.time,
    file = event.file
})

table.insert(entryList, {
    name = "Normal",
    index = #validEntries
})

if love.filesystem.exists(cLevel.."randomSongs.json") then
	local entries = dpf.loadJson(cLevel.."randomSongs.json", {})
	for _, v in ipairs(entries) do
		if love.filesystem.exists(cLevel..v.file) then
			table.insert(validEntries, {bpm = v.bpm or event.bpm, timeOffsetSeconds = v.offset or event.offset, beatOffset = event.time, file = v.file})
			local displayName = v.name or v.file
			table.insert(entryList, {name = displayName, index = #validEntries})
		else
			print(cLevel..v.file .. " doesn't exist what the freak")
		end
	end
end

--if type(cs.level.properties.songChoice) == "number" and false then
--	event = helpers.copy(validEntries[helpers.clamp(cs.chosenIndex, 1, #validEntries)])
--else
if extrasavedata.randomSongs then
	event = helpers.copy(validEntries[math.random(1, #validEntries)])
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "levelformat/events/Gameplay/play.lua"
pattern = '''
Event.property(event,'decimal', 'offset', 'Offset of the song, in seconds.', {optional = true, step = .001, default = 0, min = 0})
'''
position = "after"
payload = '''
if extrasavedata.randomSongs then
	if not love.filesystem.exists(cLevel.."randomSongs.json") then
		if imgui.Button("Generate RanSongJSON") then
			dpf.loadJson(cLevel.."randomSongs.json", {{bpm=event.bpm, timeOffsetSeconds=event.offset or 0, file="template.ogg"}})
			love.system.openURL("file://" .. love.filesystem.getRealDirectory(cLevel) .. '/' .. cLevel .. "randomSongs.json")
		end
		if imgui.IsItemHovered() then
			imgui.SetNextWindowSize(imgui.ImVec2_Float(300, 0))
			if imgui.BeginTooltip() then
				imgui.TextWrapped("Generates a template randomSong json.\nThe event's properties are automatically inserted into the song pool.\nEverything but the file property is optional.")
				imgui.EndTooltip()
			end
		end
	end
end
'''
match_indent = true